ecommerce/config/routes.rb
Rails.application.routes.draw do
  resources :categorias
  resources :produtos
  resources :index
  resources :layouts
  resources :pessoas_enderecos
  resources :pesquisas_enderecos do
    get :busca_endereco, on: :collection
  end

  match '/busca_principal', to: 'index#busca_principal', via: :post

  root 'index#index'

end

ecommerce/app/models/categoria.rb
class Categoria < ActiveRecord::Base

  has_many :produtos, dependent: :destroy

  validates_presence_of :descricao, message: " campo não pode ser vazio"
  
end

ecommerce/app/models/pessoa_endereco.rb
class PessoaEndereco < ActiveRecord::Base

  belongs_to :produto

  validates_presence_of :nome, :rua, :bairro, :cidade, :uf, :cep, :numero, :produto_id, message: " campo não pode ser vazio"

  class << self
    def busca_enderecos nome = ""
      consulta = PessoaEndereco.where("nome ILIKE ?", "%" + nome + "%").order("created_at")
      consulta
    end
  end
end

ecommerce/app/models/produto.rb
class Produto < ActiveRecord::Base

  ORDENACAO = {
      (ORDEM_CRIACAO = 'created_at') => 'Ordenação',
      (MENOR_PRECO = 'valor') => 'Menores Valores',
      (MAIOR_PRECO = 'valor DESC') => 'Maiores Valores',
      (ORDEM_CRESCENTE = 'descricao') => 'Ordenar Crescente',
      (ORDEM_DESCRESCENTE = 'descricao DESC') => 'Ordenar Decrescente'
  }

  belongs_to :categoria
  belongs_to :pessoa_endereco

  validates_presence_of :descricao, :estoque, :numero_parcelas, :valor, :categoria, :imagem_produto, message: "campo não pode ser vazio"
  validates_numericality_of :numero_parcelas, :estoque, :valor_promocao, :valor, greater_than_or_equal_to: 0, message: "não é válido"

  validate :valida_numero_parcelas_por_valor
  validate :valida_valor_promocao_marcado_checkbox

  scope :ativos, -> {where(ativo: true)}

  class << self
    def busca_produtos descricao = "", categoria_id = '', ordenacao = nil
      consulta = Produto.ativos.where("descricao ILIKE ?", "%" + descricao + "%").order(ordenacao, "created_at")
      consulta = consulta.where(categoria_id: categoria_id) unless categoria_id.blank?
      consulta
    end
  end
  private
  def valida_numero_parcelas_por_valor
    errors.add :numero_de_parcelas, 'inválidas para o valor informado' if numero_parcelas > 3 && valor <= 200.00
  end

  def valida_valor_promocao_marcado_checkbox
    errors.add :valor_promocao, 'inválido quando promoção marcado' if promocao && valor_promocao <= 1
  end

end

ecommerce/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ecommerce/app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController

  def index
    @categorias = Categoria.all
  end

  def new
    @categoria = Categoria.new
  end

  def create
    parametros  = params["categoria"]
    categoria = Categoria.new(parametros)

    if categoria.save
      redirect_to edit_categoria_path(categoria), notice: 'Categoria salvo com sucesso!'
    else
      redirect_to new_categoria_path, notice: categoria.errors.full_messages.join('\n')
    end
  end

  def edit
    @categoria = Categoria.find(params[:id])
  end

  def update
    categoria =  Categoria.find(params[:id])

    if categoria.update(params[:categoria])
      redirect_to edit_categoria_path(categoria), notice: 'Categroia atualizado com sucesso!'
    else
      redirect_to edit_categoria_path, notice: categoria.errors.full_messages.join('\n')
    end
  end

  def show
    @categoria = Categoria.find(params[:id])
  end

  def destroy

    categoria = Categoria.find(params[:id])

    if categoria.destroy
      redirect_to categorias_path(categoria), notice: 'Categoria apagado com sucesso!'
    end


  end


end

ecommerce/app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
    @produtos = Produto.busca_produtos
  end

  def busca_principal
    descricao = params[:descricao]
    categoria_id = params[:busca][:categoria_id]
    ordenacao = params[:busca][:ordenacao_consulta]

    @produtos = Produto.busca_produtos descricao, categoria_id, ordenacao
  end

end

ecommerce/app/controllers/pesquisas_enderecos_controller.rb
class PesquisasEnderecosController < ApplicationController
  def index

  end

  def busca_endereco

    nome = params[:nome]
    pesquisa_endereco = PessoaEndereco.where("nome ILIKE ?", "%" + nome + "%").joins(:produto).select("produtos.descricao as produto_descricao, pessoas_enderecos.*").first

    render json: { pesquisa_endereco: pesquisa_endereco }
  end
end

ecommerce/app/controllers/pessoas_enderecos_controller.rb
class PessoasEnderecosController < ApplicationController

  before_action :set_pessoa_endereco, only: [:edit, :destroy, :update, :show]

  def index
    @pessoas_enderecos = PessoaEndereco.joins(:produto)
  end

  def new
    @pessoa_endereco = PessoaEndereco.new
  end

  def show
  end

  def create
    parametros  = params["pessoa_endereco"]
    pessoa_endereco = PessoaEndereco.new(parametros)

    if pessoa_endereco.save
      redirect_to edit_pessoa_endereco_path(pessoa_endereco), notice: 'Endereço salvo com sucesso!'
    else
      redirect_to new_pessoa_endereco_path, notice: pessoa_endereco.errors.full_messages.join('\n')
    end
  end

  def edit

  end

  def update
    pessoa_endereco =  PessoaEndereco.find(set_pessoa_endereco)

    if pessoa_endereco.update(params[:pessoa_endereco])
      redirect_to edit_pessoa_endereco_path(pessoa_endereco), notice: 'Endereço atualizado com sucesso!'
    else
      redirect_to edit_pessoa_endereco_path, notice: pessoa_endereco.errors.full_messages.join('\n')
    end
  end

  def destroy

    pessoa_endereco = PessoaEndereco.find(set_pessoa_endereco)

    if pessoa_endereco.destroy
      redirect_to pessoas_enderecos_path(pessoa_endereco), notice: 'Endereço apagado com sucesso!'
    end


  end

  def set_pessoa_endereco
    @pessoa_endereco = PessoaEndereco.find(params[:id])
  end
end

ecommerce/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  before_action :set_produto, only: [ :show, :edit, :update]

  def index
    @produtos = Produto.joins(:categoria)
  end

  def show
  end

  def new
    @produto = Produto.new
  end

  def edit

  end

  def create
    imagem = params[:produto][:imagem_produto]
    if imagem
      # Abre o diretório e grava a imagem nele
      File.open(Rails.root.join('app/assets', 'images', imagem.original_filename), 'wb') do |arquivo|
        arquivo.write(imagem.read)
      end
      # subistitui o conteúdo da variavel pelo nome da imagem
      params[:produto][:imagem_produto] = imagem.original_filename
    end

    @produto = Produto.new(params["produto"])

    if @produto.save
      redirect_to edit_produto_path(@produto), notice: 'Produto salvo com sucesso!'
    else
      render new_produto_path
    end
  end

  def update
    imagem = params[:produto][:imagem_produto]
    if imagem
      # Abre o diretório e grava a imagem nele
      File.open(Rails.root.join('app/assets', 'images', imagem.original_filename), 'wb') do |arquivo|
        arquivo.write(imagem.read)
      end
      # subistitui o conteúdo da variavel pelo nome da imagem
      params[:produto][:imagem_produto] = imagem.original_filename
    end
    produto_atualizar = Produto.find(set_produto)

    if produto_atualizar.update(params["produto"])
      redirect_to edit_produto_path(produto_atualizar), notice: 'Produto atualizado com sucesso!'
    else
      redirect_to edit_produto_path, notice: produto_atualizar.errors.full_messages.join('\n')
    end
  end

  def destroy

    produto_apaga = Produto.find(set_produto)

    if produto_apaga.destroy
      redirect_to produtos_path(produto_apaga), notice: 'Produto apagado com sucesso!'
    end

  end
  private

  def set_produto

    @produto = Produto.find(params[:id])
  end

end

ecommerce/app/helpers/application_helper.rb
module ApplicationHelper

end

ecommerce/app/views/index/_tabelas_produtos.html.erb
<div class="row">
  <% busca_principal.each do |produto| %>

    <% valor_inteiro = produto.valor.to_d %>
    <% numero_de_parcelas_inteiro = produto.numero_parcelas.to_d %>

    <div class="card" style="width: 35rem; padding-right: 25px; padding-left: 25px;">
      <%= image_tag produto.imagem_produto, class: "card-img-top", style: "width: 250px; height: 250px;" %>

      <div class="card-body" style="height: 150px;">

        <h4 class="card-title"><%= link_to "#{produto.descricao} - Estoque disponível #{produto.estoque} unidade(s) ", produto_path(produto) %></h4>
      </div>

      <ul class="list-group list-group-flush">
        <% tag_promocao = produto.valor_promocao > 0.0 ? :s : :p %>
        <%= content_tag(:li, content_tag(tag_promocao, "Preço: R$ #{number_with_precision(produto.valor, precision: 2)}"), class: "list-group-item") %>
        <%= content_tag(:li, content_tag(:p, produto.valor_promocao > 0.0 ? "Por Apenas: R$ #{number_with_precision(produto.valor_promocao, precision: 2)}" : "Sem promoção" ), class: "list-group-item") %>
        <%= content_tag(:li, content_tag(:p, "Ou por: #{produto.numero_parcelas}x de R$ #{number_with_precision(valor_inteiro / numero_de_parcelas_inteiro, precision: 2)}"), class: "list-group-item") %>
      </ul>

      <div class="card-body">
        <a href="#" class="btn btn-primary">Comprar</a>
        <a href="#" class="btn btn-primary">Carrinho</a>
      </div>

    </div>
  <% end %>
</div>

ecommerce/app/views/index/busca_principal.js.erb
$('#tabela_produtos').html("<%= j render 'tabelas_produtos', busca_principal: @produtos %>");

ecommerce/app/views/index/index.html.erb
<%= form_tag({controller: 'index', action: 'busca_principal'}, remote: true) do %>
  <div class="row" id="teste" style="padding-left: 50px; padding-bottom: 50px" >
    <div class="form-group" style="padding-left: 50px;">
      <label>Digite sua pesquisa</label>
      <%= search_field_tag('descricao', nil , class: 'form-control') %>
    </div>

    <div class="form-group" style="padding-left: 50px;">
      <label style="padding-bottom: 5px">Categoria</label><br>
      <%= collection_select(:busca, :categoria_id, Categoria.all, :id, :descricao, include_blank: "Todas" ) %>
    </div>

    <div class="form-group" style="padding-left: 50px;">
      <label style="padding-bottom: 5px">Ordenação</label><br>
      <%= select(:busca, :ordenacao_consulta, options_for_select(Produto::ORDENACAO.invert)) %>
    </div>

    <div class="form-group" style="padding-left: 50px; padding-top: 25px;">

      <%= submit_tag "Buscar", class: "btn btn-info", remote: true %>
    </div>
  </div>
<% end %>

<div id="tabela_produtos">
  <%= render partial: "tabelas_produtos", locals: { busca_principal: @produtos }%>
</div>

ecommerce/app/views/pesquisas_enderecos/_tabelas_buscas_enderecos.html.erb
<div id="buscar">
  <form>
    <div class="form-group">
      <label>Código do Endereço</label>
      <p class="form-control" id="cod_endereco"></p>
    </div>
    <div class="form-group">
      <label>Nome</label>
      <p class="form-control" id="nome_endereco"></p>
    </div>
    <div class="form-group">
      <label>Produto</label>
      <p class="form-control" id="produto_endereco"></p>
    </div>
    <div class="form-group">
      <label>Rua</label>
      <p class="form-control" id="rua_endereco"></p>
    </div>
    <div class="form-group">
      <label>Número</label>
      <p class="form-control" id="numero_endereco"></p>
    </div>
    <div class="form-group">
      <label>Bairro</label>
      <p class="form-control" id="bairro_endereco"></p>
    </div>
    <div class="form-group">
      <label>Cidade</label>
      <p class="form-control" id="cidade_endereco"></p>
    </div>
    <div class="form-group">
      <label>UF</label>
      <p class="form-control" id="uf_endereco"></p>
    </div>
    <div class="form-group">
      <label>CEP</label>
      <p class="form-control" id="cep_endereco"></p>
    </div>

  </form>
</div>

ecommerce/app/views/pesquisas_enderecos/index.html.erb
<h3>Pesquisa Endereços</h3>
  <div class="row" style="padding-bottom: 50px" >
    <div class="form-group" style="padding-left: 15px;padding-top: 20px; ">
      <label style="padding-bottom: 7px">Digite sua pesquisa</label>
      <%= search_field_tag('nome_pessoa', nil , class: 'form-control') %>
    </div>

    <div class="form-group" style="padding-left: 20px; padding-top: 52px;">
      <div class="buscar_endereco">
        <div class="row">
            <%= button_tag "Buscar", class: "btn btn-info", remote: true, type: 'button', id: 'buscar' %>
            <p id="esconde_mensagem" style="padding-top: 8px; padding-left: 6px; color: red;">Nenhuma pesquisa encontrada!</p>
        </div>
      </div>
    </div>
  </div>

<div id="tabela_busca_endereco">
  <%= render partial: 'tabelas_buscas_enderecos' %>
</div>

ecommerce/app/views/pessoas_enderecos/edit.html.erb
<% if @pessoa_endereco.errors.any? %>
  <div id="error_explanation" style="padding-bottom: 20px">
    <h3><%= pluralize(@pessoa_endereco.errors.count, "erro") %> impedem este produto de ser salvo:</h3>
    <ul>
      <% @pessoa_endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>Endereços</h3>
<%= form_for @pessoa_endereco, :html => { :multipart => true } do |pessoa_endereco| %>
  <div class="form-group" style="...">
    <%= pessoa_endereco.label :nome %>
    <%= pessoa_endereco.text_field :nome, class: 'form-control',  placeholder: 'Digite seu Nome', value: @pessoa_endereco.nome %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :produto_id %>
    <%= pessoa_endereco.collection_select(:produto_id, Produto.all, :id, :descricao, value: @pessoa_endereco.produto_id) %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :rua %>
    <%= pessoa_endereco.text_field :rua, class: 'form-control', value: @pessoa_endereco.rua %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :numero %>
    <%= pessoa_endereco.number_field :numero, class: 'form-control', value: @pessoa_endereco.numero %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :bairro %>
    <%= pessoa_endereco.text_field :bairro, class: 'form-control', value: @pessoa_endereco.bairro %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :cidade %>
    <%= pessoa_endereco.text_field :cidade, class: 'form-control', value: @pessoa_endereco.cidade %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :uf %>
    <%= pessoa_endereco.text_field :uf, class: 'form-control', value: @pessoa_endereco.uf %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :cep %>
    <%= pessoa_endereco.text_field :cep, class: 'form-control', value: @pessoa_endereco.cep %>
  </div>

  <div class="form-group" style="padding-top: 15px;">
    <%= pessoa_endereco.button 'Atualizar', type: :submit, class: "btn btn-primary"%> <%= link_to 'Voltar', pessoas_enderecos_path, class: "btn btn-primary" %>
  </div>
<% end %>

ecommerce/app/views/pessoas_enderecos/index.html.erb
<%= notice if notice.present? %>

<h3>Lista de Produtos</h3>
<div style="padding-bottom: 15px; padding-top: 10px">
  <%= link_to "Criar novo Endereço", new_pessoa_endereco_path, method: :get, class: "btn btn-primary" %>
</div>

<table class="table table-striped">
  <thead class="thead">
  <tr>
    <th scope="col">Cód. do Endereço</th>
    <th scope="col">Nome</th>
    <th scope="col">Produto</th>
    <th scope="col">Rua</th>
    <th scope="col">Número</th>
    <th scope="col">Bairro</th>
    <th scope="col">Cidade</th>
    <th scope="col">UF</th>
    <th scope="col">CEP</th>


  </tr>
  </thead>
  <tbody>
  <% @pessoas_enderecos.each do |pessoa_endereco| %>
    <tr>
      <td><%= pessoa_endereco.id %></td>
      <td><%= pessoa_endereco.nome %></td>
      <td><%= pessoa_endereco.produto.descricao %></td>
      <td><%= pessoa_endereco.rua %></td>
      <td><%= pessoa_endereco.numero %></td>
      <td><%= pessoa_endereco.bairro %></td>
      <td><%= pessoa_endereco.cidade %></td>
      <td><%= pessoa_endereco.uf %></td>
      <td><%= pessoa_endereco.cep %></td>

      <td width="80px"><%= link_to 'Editar', edit_pessoa_endereco_path(pessoa_endereco), class: "btn btn-primary" %></td>
      <td width="90px"><%= link_to 'Mostrar', pessoa_endereco_path(pessoa_endereco), class: "btn btn-primary" %></td>
      <td width="90px"><%= link_to 'Apagar', pessoa_endereco, method: :delete, class: "btn btn-danger" %></td>
    </tr>

  <% end %>
  </tbody>
</table>

ecommerce/app/views/pessoas_enderecos/new.html.erb
<% if @pessoa_endereco.errors.any? %>
  <div id="error_explanation" style="padding-bottom: 20px">
    <h3><%= pluralize(@pessoa_endereco.errors.count, "erro") %> impedem este produto de ser salvo:</h3>
    <ul>
      <% @pessoa_endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>Endereços</h3>
<%= form_for @pessoa_endereco, :html => { :multipart => true } do |pessoa_endereco| %>
  <div class="form-group" style="...">
    <%= pessoa_endereco.label :nome %>
    <%= pessoa_endereco.text_field :nome, class: 'form-control',  placeholder: 'Digite seu Nome', value: @pessoa_endereco.nome %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :produto_id %>
    <%= pessoa_endereco.collection_select(:produto_id, Produto.all, :id, :descricao) %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :rua %>
    <%= pessoa_endereco.text_field :rua, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :numero %>
    <%= pessoa_endereco.number_field :numero, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :bairro %>
    <%= pessoa_endereco.text_field :bairro, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :cidade %>
    <%= pessoa_endereco.text_field :cidade, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :uf %>
    <%= pessoa_endereco.text_field :uf, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= pessoa_endereco.label :cep %>
    <%= pessoa_endereco.text_field :cep, class: 'form-control' %>
  </div>




  <div class="form-group" style="padding-top: 15px;">
    <%= pessoa_endereco.button 'Salvar', type: :submit, class: "btn btn-primary"%> <%= link_to 'Voltar', pessoas_enderecos_path, class: "btn btn-primary" %>
  </div>
<% end %>

ecommerce/app/views/pessoas_enderecos/show.html.erb
<%= notice if notice.present? %>

<form>
  <%= form_for @pessoa_endereco do |f| %>

    <div class="form-group">
      <label for="exampleInputEmail1"><%= f.label :id %></label>
      <input type="email" class="form-control" <%= f.text_field :id, value: @pessoa_endereco.id, disabled: true %>
    </div>
    <div class="form-group">
      <label><%= f.label :nome %></label>
      <input type="text" class="form-control" <%= f.text_field :descricao, value: @pessoa_endereco.nome, disabled: true %>
    </div>
    <div class="form-group">
      <label><%= f.label :produto %></label>
      <input type="text" class="form-control" <%= f.text_field :descricao, value: @pessoa_endereco.produto.descricao, disabled: true %>
    </div>
    <div class="form-group">
      <label><%= f.label :rua %></label>
      <input type="text" class="form-control" <%= f.text_field :descricao, value: @pessoa_endereco.rua, disabled: true %>
    </div>
    <div class="form-group">
      <label><%= f.label :numero %></label>
      <input type="text" class="form-control" <%= f.text_field :descricao, value: @pessoa_endereco.numero, disabled: true %>
    </div>
    <div class="form-group">
      <label><%= f.label :bairro %></label>
      <input type="text" class="form-control" <%= f.text_field :descricao, value: @pessoa_endereco.bairro, disabled: true %>
    </div>
    <div class="form-group">
      <label><%= f.label :cidade %></label>
      <input type="text" class="form-control" <%= f.text_field :descricao, value: @pessoa_endereco.cidade, disabled: true %>
    </div>
    <div class="form-group">
      <label><%= f.label :uf %></label>
      <input type="text" class="form-control" <%= f.text_field :descricao, value: @pessoa_endereco.uf, disabled: true %>
    </div>
    <div class="form-group">
      <label><%= f.label :cep %></label>
      <input type="text" class="form-control" <%= f.text_field :descricao, value: @pessoa_endereco.cep, disabled: true %>
    </div>

    <%= link_to 'Voltar', pessoas_enderecos_path, class: "btn btn-primary" %>
  <% end %>
</form>

ecommerce/app/views/produtos/edit.html.erb
<%= notice if notice.present? %>

<h3>Produtos</h3>
<%= form_for @produto, :html => { :multipart => true } do |produto| %>
  <div class="form-group" style="...">
    <%= produto.label :descricao %>
    <%= produto.text_field :descricao, class: 'form-control',  placeholder: 'Digite a Descricão do Produto', value: @produto.descricao %>
  </div>

  <div class="form-group">
    <%= produto.label :categoria_id %>
    <%= produto.collection_select(:categoria_id, Categoria.all, :id, :descricao, value: @produto.categoria_id) %>
  </div>

  <div class="form-group">
    <%= produto.label :estoque %>
    <%= produto.number_field :estoque, class: 'form-control', value: @produto.estoque %>
  </div>

  <div class="form-group">
    <%= produto.label :valor %>
    <%= produto.text_field :valor, class: 'form-control', value: @produto.valor %>
  </div>

  <div class="form-group">
    <%= produto.label :numero_parcelas %>
    <%= produto.number_field :numero_parcelas, class: 'form-control',value: @produto.numero_parcelas %>
  </div>

  <div class="form-group">
    <%= produto.label :ativo %> <%= produto.check_box :ativo, value: @produto.ativo %>
    <%= produto.label :promocao %> <%= produto.check_box :promocao, value: @produto.promocao %>
  </div>

  <div class="form-group">
    <%= produto.label :valor_promocao %>
    <%= produto.text_field :valor_promocao, class: 'form-control', value: @produto.valor_promocao %>
  </div>

  <div class="form-group">
    <%= produto.label :imagem_produto %>
    <%= file_field(:produto, :imagem_produto, value: @produto.imagem_produto) %>
  </div>


  <div class="form-group" style="padding-top: 15px;">
    <%= produto.button 'Salvar', type: :submit, class: "btn btn-primary"%> <%= link_to 'Voltar', produtos_path, class: "btn btn-primary" %>
  </div>
<% end %>

ecommerce/app/views/produtos/index.html.erb
<%= notice if notice.present? %>

<h3>Lista de Produtos</h3>
<div style="padding-bottom: 15px; padding-top: 10px">
  <%= link_to "Criar novo Produto", new_produto_path, method: :get, class: "btn btn-primary" %>
</div>

<table class="table table-striped">
  <thead class="thead">
  <tr>
    <th scope="col">Cód. do Produto</th>
    <th scope="col">Descrição</th>
    <th scope="col">Categoria</th>
    <th scope="col">Estoque</th>
    <th scope="col">Ativo</th>
    <th scope="col">Promoção</th>
    <th scope="col">Número de Parcelas</th>
    <th scope="col">Valor de Promoção</th>
    <th scope="col">Valor</th>


  </tr>
  </thead>
  <tbody>
  <% @produtos.each do |produto| %>
    <tr id="<%= produto.id %>">
      <td><%= produto.id %></td>
      <td><%= produto.descricao %></td>
      <td><%= produto.categoria.descricao %></td>
      <td><%= produto.estoque %></td>
      <td><%= produto.ativo %></td>
      <td><%= produto.promocao %></td>
      <td><%= produto.numero_parcelas %></td>
      <td><%= produto.valor_promocao %></td>
      <td><%= produto.valor %></td>

      <td width="80px"><%= link_to 'Editar', edit_produto_path(produto), class: "btn btn-primary" %></td>
      <td width="90px"><%= link_to 'Mostrar', produto_path(produto), class: "btn btn-primary" %></td>
      <td width="90px"><%= link_to 'Apagar', produto, method: :delete, class: "btn btn-danger" %></td>
    </tr>

  <% end %>
  </tbody>
</table>

ecommerce/app/views/produtos/new.html.erb
<% if @produto.errors.any? %>
  <div id="error_explanation" style="padding-bottom: 20px">
    <h3><%= pluralize(@produto.errors.count, "erro") %> impedem este produto de ser salvo:</h3>
    <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>Produtos</h3>
<%= form_for @produto, :html => { :multipart => true } do |produto| %>
  <div class="form-group" style="...">
    <%= produto.label :descricao %>
    <%= produto.text_field :descricao, class: 'form-control',  placeholder: 'Digite a Descricão do Produto', value: @produto.descricao %>
  </div>

  <div class="form-group">
    <%= produto.label :categoria_id %>
    <%= produto.collection_select(:categoria_id, Categoria.all, :id, :descricao) %>
  </div>

  <div class="form-group">
    <%= produto.label :estoque %>
    <%= produto.number_field :estoque, class: 'form-control' %>
  </div>

 <div class="form-group">
   <%= produto.label :valor %>
   <%= produto.text_field :valor, class: 'form-control' %>
 </div>

  <div class="form-group">
    <%= produto.label :numero_parcelas %>
    <%= produto.number_field :numero_parcelas, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= produto.label :ativo %> <%= produto.check_box :ativo %>
    <%= produto.label :promocao %> <%= produto.check_box :promocao %>
  </div>

  <div class="form-group">
    <%= produto.label :valor_promocao %>
    <%= produto.text_field :valor_promocao, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= produto.label :imagem_produto %>
    <%= file_field(:produto, :imagem_produto) %>
  </div>


  <div class="form-group" style="padding-top: 15px;">
    <%= produto.button 'Salvar', type: :submit, class: "btn btn-primary"%> <%= link_to 'Voltar', produtos_path, class: "btn btn-primary" %>
  </div>
<% end %>